<a href="https://colab.research.google.com/github/tomarrambali/FDS-Labfile/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Write a Numpy program to get the Numpy version.

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


 Q2. Write a NumPy program to test whether none of the
elements of a given array are zero.

In [ ]:
import numpy as np
arr=np.array([2,3,4,5,68])
print(arr)
print(np.all(arr))


[ 2  3  4  5 68]
True


Q3. Write a NumPy program to create an element-wise
comparison (greater, greater_equal, less and less_equal) of
two given arrays.

In [ ]:

# numpy.greater method
# numpy.less method
# numpy.greater equal Method
# numpy.less equal method is used in solve this problem
import numpy as np
arry1=np.array([1,2,3,4,5,6])
arry2=np.array([2,6,7,8,9,10])
print("greater",np.greater(arry1,arry2))
print("greater_equal",np.greater_equal(arry1,arry2))
print("less",np.less(arry1,arry2))
print("less_equal",np.less_equal(arry1,arry2))




greater [False False False False False False]
greater_equal [False False False False False False]
less [ True  True  True  True  True  True]
less_equal [ True  True  True  True  True  True]


Q4. Write a NumPy program to create an array with the values
1, 7, 13, 105 and determine the size of the memory occupied
by the array.

In [ ]:
import numpy as np
data=np.array([1,7,13,105])
print("Size of the memory occupied by the said array:")
print(data.size*data.itemsize,"Bytes")


Size of the memory occupied by the said array:
32 Bytes


Q5. Write a NumPy program to create an array of integers
from 30 to 70.

In [ ]:
import numpy as np
# numpy.arange method
arr = np.arange(30,70)
print("\n from 30,70 integer:\n" ,arr)


 from 30,70 integer:
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


 Q6. Write a NumPy program to create an array of all even
integers from 30 to 70.

In [ ]:
import numpy as np
#numpy.arrang methode is use the and the 30 is first number and 70 is the second number and last two number is divisible number
arr = np.arange(30,70,2)
print("\n from 30,70 to even  integer:\n" ,arr)


 from 30,70 to even  integer:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Q7.  Write a NumPy program to create a 3x3 identity matrix.
Write a search NumPy program to create a 3X4 array and
iterate over it.

In [ ]:
import numpy as np
a = np.arange(101,110).reshape((3, 3))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
      print(x,end="" )

Original array:
[[101 102 103]
 [104 105 106]
 [107 108 109]]
Each element of the array is:
101102103104105106107108109